### ISSUE TITLE
Extracting SHAKE256

### ISSUE THREAD

**Issue by samyuktha123sets** [formosa-crypto/libjade#100]
Dear Team, 

I am trying to utilise the SHAKE256 in the libjade library. Is there an extracted SHAKE256 file and would like to know about .jinc extension files. Can you provide any documentation on how I can include jinc files with my C code.

Looking forward to your reply.

Regards
Samyuktha

**Comment by tfaoliveira** [comment]
Hi! Perhaps the most convenient solution is the following:
1. Download the latest [release](https://github.com/formosa-crypto/libjade/releases/download/release%2F2023.05-1/libjade-dist-src-amd64.tar.gz)
2. After extracting it, go to folder `libjade-dist-src-amd64/libjade/crypto_xof/shake256_ref`
3. run `make` to compile an example from C code
4. run `./example` to see what it looks like:
```
// {"SHAKE256" : { architecture : "amd64", implementation : "ref"} }
uint8_t input[3] = {
  0x61, 0x62, 0x63
};
uint8_t output[12] = {
  0x48, 0x33, 0x66, 0x60, 0x13, 0x60, 0xa8, 0x77, 0x1c, 0x68, 0x63, 0x08
}
```

---

More detailed explanation next (using shake256 as an example). The following files are available for each implementation in the distribution (there is an exception, `libjade/crypto_sign/falcon_falcon512_avx2/`):
1. A `.jazz` file (`shake256_ref.jazz`) that contains the preprocessed code
2. A `.s` file (`shake256_ref.s`) that contains the assembly code compiled with latest Jasmin compiler release at the time of the Libjade release; I believe, in this case, Jasmin 2022.09.03
3. The corresponding header file for C applications (`shake256_ref.h`)
4. An example C file (example.c) that allows people to experiment with the code quickly
5. A Makefile to build the example executable (and rebuild the assembly file if needed).

If you have a Jasmin compiler available in your system and wish to compile the assembly file yourself: 
```
$ rm shake256_ref.s
$ make __shake256_ref.s
```

Let us know if this information is sufficient for you to proceed. 
Don't hesitate to ask if you need to do something more specific.

**Comment by samyuktha123sets** [comment]
Is there a community where we can post doubts on jasmin coding and what are .jinc files

**Comment by vbgl** [comment]
https://github.com/jasmin-lang/jasmin/wiki/Get-support

**Comment by samyuktha123sets** [comment]
Hey am facing a basic error in Jasmin and I am new to Jasmin. Can you help in resolving this error
Hello I just started learning Jasmin. I am facing this error and I do not know how to correct it. 
export fn gf16_add(reg u8 a, reg u8 b) -> reg u8{
    a ^= b;
    return a;
}
the error i get is 
"ffarithmetic.jazz", line 1 (0) to line 5 (1):
compilation error:
register allocation: cannot allocate a.182 into RAX.67, the variable is already allocated in RDI.60
make: *** [Makefile:8: ffarithmetic.s] Error 1

**Comment by tfaoliveira** [comment]
Hi! Are you happy with the first reply to this issue / were you able to experiment with the Jasmin code with C code? If so, we can close the issue.

W.r.t. the last question, since you sent me a message via Zulip, I will reply to it in a moment :-)

Nonetheless, feel free to open issues here whenever you have other questions related to libjade. One issue per topic is greatly appreciated!
