### ISSUE TITLE
bit.jinc syntax error

### ISSUE THREAD

**Issue by dderjoel** [formosa-crypto/libjade#66]
Hi,
I'm getting the following error

```
root@fc8f5c17d6fa:~/jasmin/libjade/src/crypto_scalarmult/curve25519/amd64/mulx# make
"/root/jasmin/libjade/src/crypto_scalarmult/curve25519/amd64/common/bit.jinc", line 11 (2-17)
  from "curve25519.jinc", line 76 (2-26)
  from "curve25519.jinc", line 113 (4) to line 114 (70)
  from "curve25519.jinc", line 138 (2-40)
  from "curve25519.jinc", line 173 (2-39)
  from "scalarmult.jazz", line 14 (2-31):
compilation error in function jade_scalarmult_curve25519_amd64_mulx_base:
asmgen: invalid rexpr for oprd (RSI & ((64u) 63))
        invalid rexpr for word
make: *** [../../../../Makefile.common:68: scalarmult.s] Error 1

```

I feel its line 11 in `bit.jinc` which states
```jasmin
  bit >>= p & 63;
```
I am no expert, but when I change it to
```jazz
  bit >>= p;
  bit &= 63;
``` 
the compilation works. 
It feels correct, because `p &= 7;` just before, so `bit >>= (p&63)` does not make much sense.

**Comment by vbgl** [comment]
You need a bleeding edge version of the Jasmin compiler to compile the development version of libjade: either the head of the [release-2022.09](https://github.com/jasmin-lang/jasmin/tree/release-2022.09) branch (my own recommendation) or the a recent version of the [main](https://github.com/jasmin-lang/jasmin/tree/main) branch (what the libjade developers do).

**Comment by dderjoel** [comment]
I see. 
I've done the instructions from Sir Cryptojedi [here](https://cryptojedi.org/programming/jasmin.shtml) a couple days ago, which felt like it was pulling from main, but instead I'm getting the version @VERSION@.
```
jasminc -version
Jasmin Compiler @VERSION@
```

using `opam install jasmin` now, and it compiles with the code in the repo.
(but it wont compile with my altered code anymore, which I find surprising: It fails with 
```
compilation error in function jade_scalarmult_curve25519_amd64_mulx_base:
asmgen: invalid rexpr for oprd (RDI >> RDX)
        invalid rexpr for word
make: *** [../../../../Makefile.common:68: scalarmult.s] Error 1
```)
(also the version information is not particularly helpful)

**Comment by vbgl** [comment]
Yes, there is no instruction on x86 that implement that kind of shift. Fortunately, there is one that does `RDI >> (RDX & 63)`.

**Comment by vbgl** [comment]
>  (also the version information is not particularly helpful)

The installation instruction that you’ve followed suggested to pull the Jasmin source code from the wrong repo…

**Comment by dderjoel** [comment]
> Yes, there is no instruction on x86 that implement that kind of shift. Fortunately, there is one that does `RDI >> (RDX & 63)`.

Hm, I see `shrd r/64, r/64, r32b` and `shr r/64, cl` in the manual. Former needs `BMI2`. 
All shifts only make sense with a one-byte COUNT.

So shouldn't `jasminc` be able to move `p` into `cl` and use `shr rzx, cl`, or use `shrx` (Im not sure if ISEs are enabled).
What I'm trying to understand it why does the COUNT need to be ANDed with 63, where this is clearly too big for any shifts.



> The installation instruction that you’ve followed suggested to pull the Jasmin source code from the wrong repo…

Fiat, I'll let cryptojedi know,  to change `jasmin-lang/jasmin` to `jasmin-lang/jasmin-compiler`
However, I still seem to face the issue that `jasminc -version` responds with `@VERSION@`. Is that because I've used `opam install jasmin` rather than cloning from the `release-2022.09` branch?

**Comment by vbgl** [comment]
> why does the COUNT need to be ANDed with 63

This is what x86 processors do.

**Comment by dderjoel** [comment]
Yes, I'm sorry. Got confused. I my head it was AND'ing with 2^63 (which is too big). All makes sense now. Manual says `COUNT AND 3FH` and then successive `/2`s.

**Comment by tfaoliveira** [comment]
Even though this issue is closed, the following commits, which are related to this discussion, might be of interest to readers:

https://github.com/jasmin-lang/jasmin/commit/678bd31cf80099c00c9a954416d58711de0a7758

https://github.com/formosa-crypto/libjade/commit/443ee3c2692df4882305734cd0f834dac688cbed

https://github.com/formosa-crypto/libjade/commit/fecec47e83817b56bb9166bd783d7df7d80c6d6d
